[package]
name = "tinyhttp"
version = "0.1.0"
authors = ["zhangboyu"]

[dependencies]
bytes = "0.4.7"
http="0.1.5"
httparse = "1.2.4"
tokio-io = "0.1.6"
tokio = "0.1.6"
serde="1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
time = "0.1.40"